// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: grpc/centralog.proto

package centralog_agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogsClient is the client API for Logs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogsClient interface {
	FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (Logs_FollowLogsClient, error)
}

type logsClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsClient(cc grpc.ClientConnInterface) LogsClient {
	return &logsClient{cc}
}

func (c *logsClient) FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (Logs_FollowLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Logs_ServiceDesc.Streams[0], "/Logs/FollowLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &logsFollowLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Logs_FollowLogsClient interface {
	Recv() (*Log, error)
	grpc.ClientStream
}

type logsFollowLogsClient struct {
	grpc.ClientStream
}

func (x *logsFollowLogsClient) Recv() (*Log, error) {
	m := new(Log)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogsServer is the server API for Logs service.
// All implementations must embed UnimplementedLogsServer
// for forward compatibility
type LogsServer interface {
	FollowLogs(*FollowLogsRequest, Logs_FollowLogsServer) error
	mustEmbedUnimplementedLogsServer()
}

// UnimplementedLogsServer must be embedded to have forward compatible implementations.
type UnimplementedLogsServer struct {
}

func (UnimplementedLogsServer) FollowLogs(*FollowLogsRequest, Logs_FollowLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowLogs not implemented")
}
func (UnimplementedLogsServer) mustEmbedUnimplementedLogsServer() {}

// UnsafeLogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsServer will
// result in compilation errors.
type UnsafeLogsServer interface {
	mustEmbedUnimplementedLogsServer()
}

func RegisterLogsServer(s grpc.ServiceRegistrar, srv LogsServer) {
	s.RegisterService(&Logs_ServiceDesc, srv)
}

func _Logs_FollowLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogsServer).FollowLogs(m, &logsFollowLogsServer{stream})
}

type Logs_FollowLogsServer interface {
	Send(*Log) error
	grpc.ServerStream
}

type logsFollowLogsServer struct {
	grpc.ServerStream
}

func (x *logsFollowLogsServer) Send(m *Log) error {
	return x.ServerStream.SendMsg(m)
}

// Logs_ServiceDesc is the grpc.ServiceDesc for Logs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Logs",
	HandlerType: (*LogsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FollowLogs",
			Handler:       _Logs_FollowLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/centralog.proto",
}
